# Generated by Django 3.1.3 on 2020-12-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='scientific_name',
            field=models.CharField(max_length=250),
        ),
    ]
